const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const VIDEO_FILE = path.join(__dirname, '../anime.mp4');
const OUTPUT_DIR = path.join(__dirname, '../public/frames');

console.log('⚔️  Demon Slayer Frame Extractor Starting...');
console.log(`Source Video: ${VIDEO_FILE}`);
console.log(`Output Directory: ${OUTPUT_DIR}\n`);

// 1. Verify source video exists
if (!fs.existsSync(VIDEO_FILE)) {
  console.error('❌ Error: Source video "anime.mp4" not found in the project root.');
  process.exit(1);
}

// 2. Check if FFmpeg is installed
let ffmpegCmdPath = 'ffmpeg';
let hasFfmpeg = false;

try {
  execSync('ffmpeg -version', { stdio: 'ignore' });
  hasFfmpeg = true;
} catch (e) {
  hasFfmpeg = false;
}

// Windows WinGet Packages fallback if not in global PATH yet
if (!hasFfmpeg && process.platform === 'win32') {
  const userProfile = process.env.USERPROFILE || process.env.HOMEPATH || '';
  if (userProfile) {
    const wingetDir = path.join(userProfile, 'AppData/Local/Microsoft/WinGet/Packages');
    if (fs.existsSync(wingetDir)) {
      const findFfmpeg = (dir) => {
        try {
          const files = fs.readdirSync(dir);
          for (const file of files) {
            const fullPath = path.join(dir, file);
            let stat;
            try {
              stat = fs.statSync(fullPath);
            } catch {
              continue;
            }
            if (stat.isDirectory()) {
              const found = findFfmpeg(fullPath);
              if (found) return found;
            } else if (file.toLowerCase() === 'ffmpeg.exe') {
              return fullPath;
            }
          }
        } catch {
          // ignore read errors
        }
        return null;
      };

      const foundPath = findFfmpeg(wingetDir);
      if (foundPath) {
        ffmpegCmdPath = `"${foundPath}"`;
        hasFfmpeg = true;
        console.log(`🔍 Found portable FFmpeg in WinGet directory: ${foundPath}`);
      }
    }
  }
}

if (!hasFfmpeg) {
  console.warn('⚠️  FFmpeg is not installed or not found in your system PATH.');
  console.log('------------------------------------------------------------');
  console.log('📥 HOW TO INSTALL FFMPEG:');
  console.log('------------------------------------------------------------');
  console.log('Windows (PowerShell as Administrator):');
  console.log('  winget install FFmpeg');
  console.log('  (Close and reopen your terminal after installation)');
  console.log('\nmacOS (Homebrew):');
  console.log('  brew install ffmpeg');
  console.log('\nLinux (Ubuntu/Debian):');
  console.log('  sudo apt update && sudo apt install ffmpeg');
  console.log('------------------------------------------------------------');
  console.log('ℹ️  FALLBACK MODE ACTIVE:');
  console.log('The web application will run in dynamic video-scrubbing mode.');
  console.log('You can still run this script once FFmpeg is installed to generate frames.');
  console.log('------------------------------------------------------------\n');
  process.exit(0);
}

// 3. Create output directory if it doesn't exist
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// 4. Clean existing frames to prevent mixed-sequence frames
console.log('🧹 Cleaning old frames from public/frames/...');
const files = fs.readdirSync(OUTPUT_DIR);
let cleanCount = 0;
for (const file of files) {
  if (file.startsWith('frame_') && file.endsWith('.webp')) {
    fs.unlinkSync(path.join(OUTPUT_DIR, file));
    cleanCount++;
  }
}
if (cleanCount > 0) {
  console.log(`Removed ${cleanCount} old WebP frame(s).`);
}

// 5. Run FFmpeg command to extract frames
// We scale to 1280:-1 (720p width) and use fps=24 to optimize network load and rendering speed.
// -q:v 80 is the quality level for WebP frames.
const ffmpegCmd = `${ffmpegCmdPath} -i "${VIDEO_FILE}" -vf "fps=24,scale=1280:-1" -c:v libwebp -q:v 80 -f image2 -y "${path.join(OUTPUT_DIR, 'frame_%04d.webp')}"`;

console.log('🎬 Extracting frames via FFmpeg (this might take a few seconds)...');
console.log(`Running: ${ffmpegCmd}`);

try {
  execSync(ffmpegCmd, { stdio: 'inherit' });
  
  // Verify that frames were actually created
  const resultingFiles = fs.readdirSync(OUTPUT_DIR).filter(f => f.startsWith('frame_') && f.endsWith('.webp'));
  if (resultingFiles.length === 0) {
    throw new Error('No frames were generated by FFmpeg.');
  }
  
  console.log('\n✨ SUCCESS! Frame extraction complete.');
  console.log(`Generated ${resultingFiles.length} optimized WebP frames.`);
  console.log(`Location: /public/frames/`);
  console.log(`First frame: ${resultingFiles[0]}`);
  console.log(`Last frame: ${resultingFiles[resultingFiles.length - 1]}`);
} catch (error) {
  console.error('\n❌ Error: Failed to extract frames via FFmpeg.');
  console.error(error.message);
  process.exit(1);
}
